server:
  servlet:
    context-path: /servico-cliente/api
    
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

spring:
 application:
  name: servico-cliente-ms

 datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/clientemsdb?currentSchema=cliente-ms}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:admin}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1000000
      
logging:
  level:
    com.github.joanersoncosta.servico_cliente_api: ${LOG_LEVEL:DEBUG}

springdoc:
 openapi:
  title: Cliente API
  description: Micro-Serviço de Cliente
  version: 1.0.0