spring:
 application:
  name: servico-cliente-ms

server:
  servlet:
    context-path: /servico-cliente/api

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      
springdoc:
 openapi:
  title: Cliente API
  description: Micro-Serviço de Cliente
  version: 1.0.0